# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a83225bcf5e1c46a0cb428827280d913274d7ec9e4a903f73081a60218ddd617595acb0f3604c93ea8a6a94a0164ef5a40c4d56b1386794efd9f800062a0879b

test:
  secret_key_base: 198475e27dd4212af6dcce8fab2ebe74489c678de2767618a6c98c61579e82d65f9c1344dfba9f37217caca9e762729321de818dbc1c83fa70551d8dfe478149

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
